### ISSUE TITLE
How should maps and hexes actually function?

### ISSUE THREAD

**Issue by manik1235** [manik1235/story_time#28]
I think it will depend on how the map is actually done.

1. Will it be a bunch of individual hexes stitched together?

2. Or will it be a single image chopped in to hexes?

I think #2 is more likely.

@dreckmal , what do you think? Are you able to post any examples of maps that you may be playing with?

**Comment by dreckmal** [comment]
@manik1235 , this is actually a super huge question. Either approach has pros and cons from a D&D standpoint. 

I am leaning hard on #2, because I want as many aspects of the project to be intentional as possible. 

Out of curiosity, are there huge drawbacks or concerns with either approach from a dev standpoint?

I don't have any map images that I can really share at this point. Any that I had were disposed of when shared IP issues arose.

**Comment by manik1235** [comment]
> Out of curiosity, are there huge drawbacks or concerns with either approach from a dev standpoint?

1. Will it be a bunch of individual hexes stitched together?
Con: It can be hard to make individual items tile nicely when placed next to each other.
Pro: A single tile can be reused a bunch for common areas
Con: Each tile needs to be individually defined.

2. Or will it be a single image chopped in to hexes?
Pros: No issue with transitions between tiles.
Cons: Overlaying a hex grid on the map can lead to difficult boundary conditions. (e.g. the hexes line up nicely on the coast, but other hexes straddle the inside and outside of a castle. Fixing the castle shifts the hexes so now they're straddling the coast, instead of lined up nicely.
- I think this is a minor `con`, though, because it can be fixed with the hex definitions, or even just by taking in to account what is actually under the hex.
Cons: If the map has pre-drawn hexes, getting them to line up well with the computed hex boundaries can be difficult, especially if the pre-drawn lines are stretched or skewed a bit.

Technically we could support both methods, just at the cost of increased dev time. I'd prefer adopting one to start, and adding the other as a feature, later, so probably #2.

**Comment by manik1235** [comment]
@dreckmal Since you are already planning on running this game as a podcast, with or without a website, how do you think you'll be making your map for the podcast? I think that'll be a good first method to implement.

**Comment by manik1235** [comment]
Also, as a bit of background, I made a map editor for a game a few years ago. It used tiles and placed them together (e.g. method #1 above). It worked nicely, but getting the tiling to look nice was difficult and definitely added complexity.

I think having a single map that gets chopped up will be the easiest for the podcast format, so that the map being used isn't relying on the website, the website is relying on the map being used. I think that direction of dependency makes the most sense, especially to start.

**Comment by dreckmal** [comment]
I actually largely agree with your assessment. What little tech know-how I had/have definitely suggests drawing each hex is likely much more 'expensive' both in dev time and literal hardware usage.

**Comment by dreckmal** [comment]
> 
> 
> @dreckmal Since you are already planning on running this game as a podcast, with or without a website, how do you think you'll be making your map for the podcast? I think that'll be a good first method to implement.

I have really been struggling with this. Like really bad. I have interest in learning to use software to try and make a vector image map. But all that software seems to have a pretty steep learning curve. I don't want to ask anyone to do it for me, because I can't pay. 

I think what's going to happen is that I'm going to run off hand drawn maps (either/both digital and analog) and attempt to slowly learn to use something like Inkscape or maybe Photoshop (although I certainly can't buy photoshop).

**Comment by manik1235** [comment]
In this case, I've been looking in to using RMagick with Ruby to draw vector graphics, so that may be worth looking more in to, too, to see what all we can accomplish.

**Comment by manik1235** [comment]
Closing this issue.

We are going to be using maps that @dreckmal creates in [Campaign Cartographer](https://www.profantasy.com/products/cc3.asp)

Hexes will be overlayed, and if needed drawn on the map.

The size, rotation and offset of the hexes will be adjustable in the UI.
